version: 2

sources:
  - name: normalized_data_swavibr_calendar_settings
    description: This is a replica of the Postgres database used by our app
    tables:
      - name: calendar_settings
        columns:
        - name : a_name
        - name : identifier
        - name : a_group
        - name : a_value
        - name : id
        - name : value_op.