sources:
  - name: swavibr_loan_settings
    description: This is a replica of the Postgres database used by our app
    tables:
      - name: loan_settings
        columns:
        - name : timestamp
        - name : value
        - name : offset.